### ISSUE TITLE
Add RWSC branding to glossary

### ISSUE THREAD

**Issue by reblake** [RWSCollab/glossary-data-mgmt-gov#1]
RWSC colors, fonts, logo and any other elements from their style guide need to be added to this rendered glossary page.

**Comment by eshumchenia** [comment]
Could you pull in elements from [the Science Plan .yml](https://github.com/RWSCollab/science-plan/blob/0d17288bab196803ff6796b9b974c3f12a146c79/_quarto.yml)?

that file also calls a .scss file for additional styling: https://github.com/RWSCollab/science-plan/blob/main/rwsc.scss

I saw your note that the theme didn't work in this repo's .yml file

**Comment by reblake** [comment]
I was able to copy the `rwsc.scss` file to this repo and modify the yaml to make it look very similar to the science plan.
